name: lint and build
on: pull_request

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Dependencies
        run: pod install --repo-update
        shell: bash

      - name: Check Format
        run: Pods/SwiftFormat/CommandLineTool/swiftformat --lint .

      - name: SwiftLint
        run: Pods/SwiftLint/swiftlint

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Dependencies
        run: pod install --repo-update
        shell: bash

      - name: Build archive
        run: |
          xcodebuild archive -workspace rekey.xcworkspace -scheme rekey \
            -configuration Debug -archivePath build/rekey

      - name: Export archive
        run: |
          xcodebuild -exportArchive -archivePath build/rekey.xcarchive \
            -exportPath build/dist -exportOptionsPlist ExportOptions/Debug.plist

      - name: Create dmg
        run: |
          pushd build && ln -s /Applications && popd
          hdiutil create rekey.dmg -volname "rekey" -srcfolder build/dist

      - name: Save dmg as artifact
        uses: actions/upload-artifact@v1
        with:
          name: rekey.dmg
          path: rekey.dmg
