name: check and build
on: pull_request

jobs:
  check-and-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Dependencies
        run: pod install --repo-update
        shell: bash

      - name: Check Format
        run: Pods/SwiftFormat/CommandLineTool/swiftformat --lint .

      - name: SwiftLint
        run: Pods/SwiftLint/swiftlint

      - name: Debug Build
        run: |
          xcodebuild -workspace rekey.xcworkspace -scheme rekey -configuration Debug archive -archivePath Build/rekey

      - name: Archive product
        uses: actions/upload-artifact@v1
        with:
          name: rekey.app
          path: Build/rekey.xcarchive/Products/Applications
